version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - mongo
    entrypoint: ["./wait-for-it.sh", "mongodb-container:27018", "--", "npm", "start"]
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --port 27018 --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - mongodb-data:/data/db      
    environment:
      MONGO_INITDB_DATABASE: lanchonete
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin123

volumes:
  mongodb-data:
    driver: local
