version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - mongo    
    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27018
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --port 27018 --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - mongodb-data:/data/db      
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongodb-data:
    driver: local
