apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27018
  clusterIP: None  # Headless para comunicação interna