apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2xhbmNob25ldGUtY29zbW9zZGI6SElqZFJ2UFlreVZNOFZGSWhWN1VlUlVzdWJQRDlSTzlaVEg0bWl3WDNEQzF5ang4S0JMSjJySW16NlVZWnlBeHRJajJoN2twYlRBREFDRGJYd2JHOWc9PUBsYW5jaG9uZXRlLWNvc21vc2RiLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJldHJ5d3JpdGVzPWZhbHNlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AbGFuY2hvbmV0ZS1jb3Ntb3NkYkA=
