apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=   # base64 de "admin"
  MONGO_PASSWORD: YWRtaW4xMjM=  # base64 de "adminpass"